### PR TITLE
fix broken links

### PR DESCRIPTION
**Pull request by frabrunelle**
oops I had made some errors for the links. everything should be okay now.

can you merge this and publish the new version of the package? thank you :smile:

### CODE REVIEW

**Comment by dschulz** [comment]
Committed, thanks! I think you should own this repo. If you're ok with this, I'll transfer it to you in a few hours (I'm on mobile now).

**Comment by frabrunelle** [comment]
> If you're ok with this, I'll transfer it to you in a few hours (I'm on mobile now).

Yes, I'm ok with this :smiley: 

But I would also need to be able to update the package on [Atmosphere](https://atmospherejs.com/dschulz/jquery-qrcode).

Could you add me as a maintainer of the package by running this command?

`meteor admin maintainers dschulz:jquery-qrcode --add frabrunelle`

Otherwise I can start my own `frabrunelle:jquery-qrcode` package, but I think it's better to update the existing one. Otherwise it's more confusing for people who search for the package.

Cheers.

**Comment by dschulz** [comment]
Great! Please give me a few hours, I'll proceed as you suggested. I also think that too many similar packages in atmosphere is confusing.

**Comment by frabrunelle** [comment]
Thank you for adding me as a maintainer of the package :smile: 

I just published 1.0.2.

I also uploaded a [demo](https://jquery-qrcode.meteor.com/) ([source code](https://github.com/frabrunelle/jquery-qrcode-demo)).

Now I will wait for you to transfer me the ownership of the repository :smiley:

**Comment by dschulz** [comment]
Thanks to you! I requested the transfer, but it looks like it takes some time (currently it says "being transferred to @frabrunelle"). This is the first time I'm trying this (transfer a repo), so let's wait and see what happens next :smile: 
Anyhow, you should have push access now, as I've added you as a collaborator previously..

**Comment by frabrunelle** [comment]
Oh I had received an email from GitHub so I just needed to click on the link!

The repository is transferred now :+1:

**Pull request merged**
